version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - '5000:5000'
    env_file:
      - ./backend/.env
    depends_on:
      - db
    restart: always

  frontend:
    build: ./frontend
    ports:
      - '4173:4173'
    env_file:
      - ./frontend/.env
    depends_on:
      - backend
    restart: always

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

volumes:
  postgres_data:
